### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-client-ios-app#2]
This repo has been prepared for production.
It is necessary to enable CI.
A check is necessary if all settings in .drone.star in master and 11.7 are setup correctly

**Comment by xoxys** [comment]
Don't know what you mean... The CI is enabled already and jobs have passed as well.

**Comment by xoxys** [comment]
Keep in mind to let us know if you have changed the PDF file names or if you have published files with the wrong name...

```
-rw-r--r-- 1 root root 7.3M Sep 16 21:03 11.7_ownCloud_iOS_App_Manual.pdf
-rw-r--r-- 1 root root 7.3M Sep 16 21:03 next_ownCloud_iOS_App_Manual.pdf
-rw-r--r-- 1 root root  22K Sep 15 16:56 next_ownCloud_IOS_App_Manual.pdf
```

**Comment by mmattel** [comment]
The good news is, that there are no historic pdf files.
They will be generated first with this repo for iOS

**Comment by xoxys** [comment]
That's not what I tried to say... There is a duplicate/broken `next_ownCloud_IOS_App_Manual.pdf` due to a typo. I have removed it now.

**Comment by mmattel** [comment]
Many thanks for catching. Seems that it was a leftover from preparing the repo.

**Comment by mmattel** [comment]
I guess we can close this issue - agree?
