### ISSUE TITLE
Build options missing in the documentation

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/docs-client-ios-app#92]
`mdm_tables.adoc` also contains auto-generated documentation on available build flags that are available for branding. At the moment, this part of the documentation is not publicly visible and therefore inaccessible.

A new appendix should be added, covering the available build options for use in the `Branding.plist` file:

```
# Build options

== Introduction

The following build options are available for configuring custom builds via the `Branding.plist` file: 

include::./mdm_tables.adoc[tag=build]
```

If this should not be part of the documentation, I'd like to bring back `doc/BUILD_CUSTOMIZATION.md` to the `owncloud/ios-app` repository in its entirety to cover the gaps in documentation.

**Comment by michaelstingl** [comment]
> If this should not be part of the documentation,

Everything should be visible. Was just never added. I can check later.
